### ISSUE TITLE
[Developer] Testing Guide

### ISSUE THREAD

**Issue by jbktsang** [ischaaf/BuddingBudget#13]

**Comment by kylechu** [comment]
How to test the software (e.g., run the test suite). In some cases, the instructions may need to include information such as how to access data sources (e.g., how to create and populate a database), similarly to or in addition to what a user must do. For example if your software is a website or web service, the developer documentation must include everything a programmer must do in order to get a test version of the website up and running your software. You may reference the user documentation to avoid duplication.
