### ISSUE TITLE
[Developer] Release Guide

### ISSUE THREAD

**Issue by jbktsang** [ischaaf/BuddingBudget#14]

**Comment by kylechu** [comment]
How to release a new version of your software. After you are happy that a new version of your product is ready to be released, making a release involves steps such as:

updating revision numbers in your code and documentation.
creating the zip file, tar file, or other package that a user or developer will download to obtain your product. If you have multiple downloads (say, a source and a binary release), then each must be created.
copying files to your website, so that the new version is visible to the world.
sanity-checking that the website and downloadable files are as you wish. For instance, after making a release but before publicizing it, you should check that all the links work, download the software from a fresh account (with none of your own personal customizations) and run its tests, etc.
Your instructions should make clear how to control the website to which your files are copied. For example, it is recommended that a developer can create a private release (sometimes called a testing release). That way, you can test your software without breaking the publicly-available version.

It is permissible, but not required, to create a testing release on an automated schedule (say, every night). However, you should update your main public release only when your code is in a stable state for ordinary users.

**Comment by hamsummit** [comment]
still have some open points in the drive, not sure about all the steps
